//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace film
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotaryRole
    {
        public int Id { get; set; }
        public int FilmId { get; set; }
        public bool IsWinner { get; set; }
        public int LotaryId { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Lotary Lotary { get; set; }
    }
}
